import Card from "../common/Card";
import { Radar, Thermometer, Waves } from "lucide-react";

const prediction = JSON.parse(
  localStorage.getItem("latestPrediction") || "{}"
);

const probabilities = prediction.sensor_probabilities || {};

const sensors = [
  {
    name: "Radar",
    confidence: (probabilities.radar ?? 0) * 100,
    color: "#06b6d4",
    status: "Excellent",
    icon: <Radar size={18} />,
  },
  {
    name: "Thermal",
    confidence: (probabilities.thermal ?? 0) * 100,
    color: "#f59e0b",
    status: "Good",
    icon: <Thermometer size={18} />,
  },
  {
    name: "Acoustic",
    confidence: (probabilities.acoustic ?? 0) * 100,
    color: "#8b5cf6",
    status: "Stable",
    icon: <Waves size={18} />,
  },
];

const SensorContributionChart = () => {
  return (
    <Card>
      <div className="mb-8">
        <h2 className="text-xl font-semibold text-white">
          Current Sensor Confidence
        </h2>

        <p className="mt-2 text-sm text-slate-400">
          Individual confidence generated by each uploaded sensor before
          adaptive fusion.
        </p>
      </div>

      <div className="space-y-8">
        {sensors.map((sensor) => (
          <div key={sensor.name}>
            <div className="mb-3 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div
                  className="rounded-lg p-2"
                  style={{
                    backgroundColor: `${sensor.color}20`,
                    color: sensor.color,
                  }}
                >
                  {sensor.icon}
                </div>

                <div>
                  <p className="font-semibold text-white">
                    {sensor.name}
                  </p>

                  <p className="text-xs text-slate-500">
                    {sensor.status}
                  </p>
                </div>
              </div>

              <span className="text-lg font-semibold text-white">
                {sensor.confidence.toFixed(1)}%
              </span>
            </div>

            <div className="h-3 overflow-hidden rounded-full bg-slate-800">
              <div
                className="h-full rounded-full transition-all duration-1000"
                style={{
                  width: `${sensor.confidence}%`,
                  backgroundColor: sensor.color,
                }}
              />
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4">
        <p className="text-sm leading-6 text-slate-300">
          These values are read directly from the backend response for the
          latest prediction. The{" "}
          <span className="font-semibold text-cyan-400">
            BQPhy Quantum-Inspired Optimization
          </span>{" "}
          module uses these sensor confidences to generate the optimized fusion
          weights before producing the final prediction.
        </p>
      </div>
    </Card>
  );
};

export default SensorContributionChart;